### ISSUE TITLE
Impossible levels?

### ISSUE THREAD

**Issue by rsalmei** [wiryls/project.cc.alpha#3]
Hey, congrats!
It's a very smart game, I like it a lot!

But it seems some levels are impossible, or some mechanics are missing from the readme...
For example in triangle power, how is anyone supposed to pass through this line of three reds, totally closing the passage?
<img width="899" alt="image" src="https://github.com/wiryls/cube-collection/assets/6652853/9a09c8ef-454e-49de-9c6d-72d88918d9c7">

**Comment by wiryls** [comment]
Oh, it's the first issue in this repository!

All levels can be passed within rules. You may notice that as long as any cube (including white cube) occupies all end points, the level is cleared. And in this level, you can find a way to move the **RED** cubes to the end points.

If you are still not sure how to pass through, tell me and I'll record a gif.

**Comment by rsalmei** [comment]
Wow, I'd really like a gif if you can... thank you!

**Comment by wiryls** [comment]
> Wow, I'd really like a gif if you can... thank you!

![triangle](https://github.com/wiryls/cube-collection/assets/7984500/dce3e0aa-a7af-4000-8e5e-beb1bc313a88)

This level (triangle power) uses the implicit rules shown in its previous two levels:

1. What happens if two red cubes absorb a same green cube at the same time?
   - They will be merged into one.
3. What happens to their motion when being merged?
   - They will move if there is no movement conflict.

It’s also worth mentioning that all the cubes in this level are composed of four basic cubes (which gives an illusion). Thus the solution in the picture above becomes possible.

```ascii
               ┌──────┐                 ┌──────┐
               │      │                 │      │
┌──────┐       │      │          ┌──────┘      │
│      │   │   │      │   ─────  │             │
│      │ ──┼── ├──────┤          │             │
│      │   │   │      │   ─────  │             │
└──────┘       │      │          └──────┐      │
               │      │                 │      │
               └──────┘                 └──────┘
```

**Comment by wiryls** [comment]
It seems problem solved. Feel free to create a new one or ask me to reopen this if you have any questions.

**Comment by rsalmei** [comment]
Hey, sorry for the late response.
Thank you very much for your detailed reply, very interesting!
And awesome gif! It really needed this new knowledge, that in case the red blocks cannot move in one direction, they just go the other way **the same distance**, i.e., their movement is relative, not absolute. I thought they would stop at the same spot on the right...
Well, I'm still clueless about some others but I won't bother you (too much), these two are the ones I'm most curious now... Could you give some hints, if you don't mind?
<img width="400" alt="image" src="https://github.com/wiryls/cube-collection/assets/6652853/c53483ca-257f-4fd3-a0a8-08ba3b38d146">
<img width="300" alt="image" src="https://github.com/wiryls/cube-collection/assets/6652853/f192ff9b-7559-4705-bdfd-4ed46f8aaa29">

**Comment by rsalmei** [comment]
Curiosity, did you already know about this game somewhere and just implemented it in Rust, or did you actually design it from scratch?

**Comment by wiryls** [comment]
@rsalmei oh, you are welcome. I'd like to share them with you.

> Could you give some hints, if you don't mind?

In order to pass through the first level (reincarnation), you may **put one GREEN cube between two RED cubes** and then see what happens.

I must say, this level (reincarnation) is actually an expansion of its previous one (sacrifice, also in the `README.md`). In "sacrifice", red cubes will be stuck. In this level, there is a little different, but I hope players will try the same solution.

Each level of this game has only one to three difficulties and also restarts quickly. My purpose is to encourage people to try without any fear of failure. After all, it is easy to trap players, but it is very difficult to make players find it interesting.

As for the second level (unlock), I recommend you **take a look at how *pin tumbler lock* works**. I believe if you find a video about it, suddenly you will know how to solve it. :-)

And there is a flaw in the level "unlock". So far I don’t know how to express *blocked state* of cubes. So we cannot observe that white cubes try moving to left but being blocked, which making it's difficult to unlock. (In contrast, I spent a lot of time [drawing a gap](https://github.com/wiryls/cube-collection/blob/c1e2d2fad72e087a1bc2a75b45c37d30da79dd46/cube-collection/src/plugin/scene_plugin/common/style.rs#L32-L53) to show whether the cubes are connected.) And one more thing, after watching how the pin tumbler lock works, I spent two hours designing this level on a whim. Therefore, this one is completely different from others.

> Curiosity, did you already know about this game somewhere and just implemented it in Rust, or did you actually design it from scratch?

This game originally came from an assignment in my college days. That was a prototype, simpler and rougher, written in Unity with my friends. And I was mainly responsible for the gameplay and level design. After that, I redesigned the rules twice. For now, rules were a lot different from the Unity version. So this game was designed by me from scratch.

I used to play those classic games (such as Tetris, Sokoban, etc.) a lot when I was a kid. At that time, I had a very strange idea, why do these old games only allow a single object to move? So during the course, I started designing some mechanisms to allow multiple objects moving in different directions at the same time. This is indeed difficult. There will be many problems of "dependence" and "competition". Therefore the Unity version contains many bugs. So far I have refactored the implementation three or four times to fix them (current implementation is in [`rule/collection.rs`](https://github.com/wiryls/cube-collection/blob/c1e2d2fad72e087a1bc2a75b45c37d30da79dd46/cube-core/src/rule/collection.rs#L102)).

**Comment by rsalmei** [comment]
Hey @wiryls!
That's awesome, thanks for the tips and the story behind the game origins. I appreciate it very much, it is brilliant!!
I'm still unsure about those two puzzles, but I'll try them. I mean, how can I put ONE green between the reds if they are all vertical? The other green will get stuck below the reds too... And I couldn't yet, but I'll look for how a pin tumbler lock works...

Also, whenever I have the time I intend to take a look at the code. I think I need to study bevy first or I won't understand a thing.
Thanks again, man. I won't annoy you anymore, you can close this one now 😜

**Comment by wiryls** [comment]
@rsalmei before closing this issue, I post a solution here. Please take a look if you need it.

<details>
  <summary>click to display</summary>
  <img src="https://github.com/wiryls/cube-collection/assets/7984500/0ffcfceb-ca47-44a5-9592-2055229af224" alt="preview">
</details>
